services:
  db:
    image: postgres:16
    container_name: personal-finance-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8090:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: personal-finance-app
    depends_on:
      - db
    environment:
      AUTH0_ISSUER: ${AUTH0_ISSUER}
      PERSONAL_FINANCE_AUDIENCE: ${PERSONAL_FINANCE_AUDIENCE}
      DB_PERSONAL_FINANCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  pgdata: {}
