spring:
  application:
    name: personal-finance
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER}
          audiences: ${PERSONAL_FINANCE_AUDIENCE}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_PERSONAL_FINANCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:5173}