spring.application.name=personal-finance

#Auth0 setup for resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER}
spring.security.oauth2.resourceserver.jwt.audience=${PERSONAL_FINANCE_AUDIENCE}

#Database setup
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DB_PERSONAL_FINANCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true